# Generated by Django 2.2 on 2022-11-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='acc_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
